### ISSUE TITLE
How Did you guys configured the Azure Directory??

### ISSUE THREAD

**Issue by ishqDehlvi** [uwindsorcss/css-site#19]
While working on my localhost I just created an active directory app and obtained the api's now when I logged in it's saying user nor found...

**Comment by Dante-Masciotra** [comment]
Please utilize the 'Issues' tab on GitHub to report any bugs or propose new features. If you need help with a coding issue, please use the 'dev-talk' channel on our Discord server. We have a great community that will be more than happy to give you a hand.
