### ISSUE TITLE
Event Visibility (Private/Public Events)

### ISSUE THREAD

**Issue by BorhanSaflo** [uwindsorcss/css-site#31]
Currently, all events created are public. This limitation poses challenges for staff members who may want to prepare event posts in advance or temporarily take down events without completely deleting them.

**Proposed Solution:**
Introduce a Private/Public Events toggle so staff members could create events in advance, setting them to private until they are ready for public visibility. This would allow for better event planning and coordination.

**Comment by jere-mie** [comment]
This is a pretty cool idea honestly. Kinda like how in Hugo and other like technologies, you can set a page or blog entry as "draft"

**Comment by BorhanSaflo** [comment]
Exactly

**Comment by BorhanSaflo** [comment]
Implemented: b2455d4c604169509cdf0d1ccfbed5753e93a5b5
