### ISSUE TITLE
Full Screen Image Modal

### ISSUE THREAD

**Issue by BorhanSaflo** [uwindsorcss/css-site#34]
Currently, some images within the site, such as the hierarchy of positions image on the About page, are too small to be easily readable. To improve user experience and accessibility, we can implement a full screen image modal feature. It would activate when an image is clicked, presenting a full screen close-up of the image. This will allow users to view details more clearly.

**Comment by SyndicateGit** [comment]
Is anyone currently working on this? I can take it on.

https://www.w3schools.com/howto/howto_css_modal_images.asp Found a solution online.
Edit: Found out it's in markdown. So it's not ^ this solution.

**Comment by SyndicateGit** [comment]
https://github.com/uwindsorcss/css-site/pull/50
