### ISSUE TITLE
show events page number

### ISSUE THREAD

**Issue by tanzimfh** [uwindsorcss/css-site#36]
#### Describe Problem
https://css.uwindsor.ca/events

i get anxiety looking at this

![image](https://github.com/uwindsorcss/css-site/assets/51885607/c02cb06b-b301-4af2-9bc6-5916d1975d58)

#### Suggest Solution

@BorhanSaflo pls add page number and total number of pages

**Comment by BorhanSaflo** [comment]
Resolved in 70dc4a7
