### ISSUE TITLE
add waitlist for events

### ISSUE THREAD

**Issue by tanzimfh** [uwindsorcss/css-site#37]
#### Describe Problem
People often unregister from events, and those spots are given to whoever happens to check at the right time.

#### Suggest Solution
Implement a waitlist so that people who were there first get spots that open up.

**Comment by BorhanSaflo** [comment]
Good suggestion

**Comment by jere-mie** [comment]
This was a thing for the old css site - shouldn't be too hard to add. Though you may want to implement an email system so that people are notified when they're off the wait-list. Otherwise you'll run into issues with people registered and they don't know it
